// const fakeDATA = [
//   { name: "Cas", phone: "2061111111" },
//   { name: "Rea", phone: "2062222222" },
//   { name: "Josh", phone: "2063333333" },
//   { name: "Chris", phone: "2064444444" },
//   { name: "JB", phone: "2065555555" },
//   { name: "Khai", phone: "2066666666" },
//   { name: "Koda", phone: "2067777777" },
//   { name: "Allie", phone: "2068888888" },
//   { name: "Raquel", phone: "2069999999" },
//   { name: "Ben", phone: "2060000000" },
// ];

const fakeDATA = [
  "Chris",
  "Josh",
  "castues3",
  "Pine",
  "castue5",
  "Jerry",
  "castue6",
  "Jean",
  "Chrisagain",
  "Test",
  "Twotwelve",
  "Usertest",
  "Testerererer",
  "Notuser",
  "Christest",
  "Jerm",
  "Jermy",
  "Jimbo",
  "Harry",
  "Geri",
  "Perry",
  "Phillie",
  "Larry",
  "Happinh",
  "Hope",
  "Hear",
  "Heard",
  "Heardy",
  "Beet",
  "Haro",
  "casibrahim",
  "caswednesday",
  "caswed2",
  "caswed3",
  "Rearo43 ",
  "Joseph",
  "Chrismorning",
  "Chrisreal ",
  "Chrisrealagain ",
  "Rea",
  "Christoph",
  "Jack",
  "A",
  "Joshua",
  "Z",
  "munir",
  "mun2",
  "caswedpm",
  "caswedeve",
  "caswednite",
  "Test43",
];
export default fakeDATA;
